# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
                ('icon_raw', models.ImageField(blank=True, default='', null=True, upload_to='upload/node/%Y%m%d', verbose_name="Node's icon")),
                ('icon_l', models.ImageField(blank=True, default='', null=True, upload_to='node/%Y%m%d', verbose_name='large icon')),
                ('icon_m', models.ImageField(blank=True, default='', null=True, upload_to='node/%Y%m%d', verbose_name='medium icon')),
                ('icon_s', models.ImageField(blank=True, default='', null=True, upload_to='node/%Y%m%d', verbose_name='small icon')),
                ('order', models.IntegerField(default=0)),
                ('is_trash', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['section', '-order'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=1)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('markdown', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('viewed', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('last_replied', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField(default=10)),
                ('reply_reward', models.BooleanField(default=False)),
                ('like_reward', models.BooleanField(default=False)),
                ('admin_star', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to=settings.AUTH_USER_MODEL)),
                ('liker', models.ManyToManyField(blank=True, related_name='like_topics', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='forum.Node')),
            ],
            options={
                'ordering': ['-rank', '-date_created'],
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='node',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='forum.Section'),
        ),
        migrations.AddField(
            model_name='node',
            name='watcher',
            field=models.ManyToManyField(blank=True, related_name='watch_nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
